'use client';
import { ResourceView } from '@/components/ResourceView';
import { Kanban, Gantt, CalendarView } from '@/components/views';
export default function Page() {
  return <ResourceView title="업무 (WBS)" subtitle="작업을 분해하고 진척을 관리합니다." endpoint="/api/tasks" projectScoped entity="tasks" treeKey="parentId"
    altViews={[
      { key: 'board', label: '보드', render: (rows, openDetail) => (
        <Kanban rows={rows} openDetail={openDetail} titleKey="name" columns={[
          { key: 'todo', label: '할 일', color: '#94a3b8' },
          { key: 'doing', label: '진행중', color: '#be5535' },
          { key: 'done', label: '완료', color: '#15a34a' },
        ]} />
      )},
      { key: 'gantt', label: '타임라인', render: (rows, openDetail, save, create) => <Gantt rows={rows} openDetail={openDetail} save={save} create={create} /> },
      { key: 'cal', label: '캘린더', render: (rows, openDetail) => <CalendarView rows={rows} dateKey="endDate" openDetail={openDetail} /> },
    ]}
    columns={[{key:'code',label:'코드'},{key:'name',label:'작업',strong:true},{key:'phase',label:'단계'},{key:'predecessor',label:'선행'},{key:'assignee',label:'담당'},{key:'status',label:'상태',badge:true},{key:'progress',label:'진척',render:(v)=>(<div className="row" style={{gap:8}}><div className="bar"><i style={{width:`${v||0}%`}}/></div><span className="muted" style={{fontSize:11.5}}>{v||0}%</span></div>)},{key:'actualHours',label:'공수',render:(_v,row)=>{const p=Number(row.plannedHours)||0;const a=Number(row.actualHours)||0;if(!p&&!a)return <span className="muted" title="계획·실제 공수 미입력">—</span>;const pg=Number(row.progress)||0;const burn=p>0?Math.round(a/p*100):null;const over=p>0&&a>p;const col=over?'#c0414f':burn!=null&&burn>=80?'#d98a16':'#2f8f5b';const gap=burn!=null&&pg>0?burn-pg:null;const num=(n:number)=>String(Math.round(n*10)/10);const tip=[p?`계획 ${num(p)}h`:'계획 공수 미입력',`실제 ${num(a)}h`,burn!=null?`소진율 ${burn}%`:null,p>0?(over?`${num(a-p)}h 초과`:`잔여 ${num(p-a)}h`):null,gap!=null&&Math.abs(gap)>=20?(gap>0?`진척 ${pg}%보다 공수 소진이 ${Math.round(gap)}%p 앞섬 — 효율 저하 주의`:`진척 ${pg}%이 공수 소진보다 ${Math.round(-gap)}%p 앞섬 — 효율 양호`):null].filter(Boolean).join(' · ');return <div className="row" title={tip} style={{gap:8,cursor:'help',whiteSpace:'nowrap'}}><span style={{fontVariantNumeric:'tabular-nums',fontSize:11.5,color:over?'#c0414f':undefined,fontWeight:over?700:undefined}}>{num(a)}<span className="muted">{` / ${p?num(p)+'h':'—'}`}</span></span>{burn!=null&&<div className="bar" style={{width:44,minWidth:44}}><i style={{width:`${Math.min(100,burn)}%`,background:col}}/></div>}{over&&<span style={{color:'#c0414f',fontWeight:700,fontSize:11}}>⚠</span>}</div>;}},{key:'endDate',label:'마감'}]}
    fields={[{key:'name',label:'작업명',required:true},{key:'phase',label:'단계',type:'combo',half:true,options:['착수','요구사항 분석','분석/설계','설계','구현/개발','단위 테스트','통합 테스트','시스템 테스트','이행/전개','안정화','검수','운영/유지보수','완료'],placeholder:'단계 선택/입력'},{key:'assignee',label:'담당자',type:'combo',optionsFrom:'members',half:true,placeholder:'인력 선택/입력'},{key:'status',label:'상태',type:'select',options:['todo','doing','done'],half:true},{key:'progress',label:'진척률',type:'select',numeric:true,half:true,options:[{value:'0',label:'0%'},{value:'10',label:'10%'},{value:'20',label:'20%'},{value:'30',label:'30%'},{value:'40',label:'40%'},{value:'50',label:'50%'},{value:'60',label:'60%'},{value:'70',label:'70%'},{value:'80',label:'80%'},{value:'90',label:'90%'},{value:'100',label:'100%'}]},{key:'startDate',label:'시작일',type:'date',half:true},{key:'endDate',label:'마감일',type:'date',half:true},{key:'reqCode',label:'연계 요구사항',type:'combo',options:[],placeholder:'예: REQ-0001',hint:'요구사항 코드를 입력하면 추적(RTM)에 연결됩니다'},{key:'predecessor',label:'선행 작업',type:'combo',options:[],placeholder:'예: WBS-0001',hint:'이 작업 전에 완료돼야 할 작업 코드'},{key:'parentId',label:'상위 작업(WBS)',type:'select',optionsFrom:'tasks',numeric:true,half:true,placeholder:'없음(최상위)',hint:'상위 작업을 지정하면 1·1.1 번호와 들여쓰기로 계층 표시됩니다'},{key:'plannedHours',label:'계획 공수(h)',type:'number',numeric:true,half:true,placeholder:'예: 16'},{key:'actualHours',label:'실제 공수(h)',type:'number',numeric:true,half:true,placeholder:'예: 12',hint:'실적 시간을 입력하면 EVM의 AC·CPI가 계산됩니다'},{key:'baselineStart',label:'기준선 시작(계획)',type:'date',half:true,hint:'최초 계획 일정. 간트에서 현재 일정과 이중 막대로 비교됩니다'},{key:'baselineEnd',label:'기준선 마감(계획)',type:'date',half:true,hint:'입력하면 간트 막대 아래 옅은 기준선 막대가 표시됩니다'}]} />;
}
